### ISSUE TITLE
Problem programming dsPIC33EP512GP504

### ISSUE THREAD

**Issue by Keritan** [thirtythreeforty/bullycpp#21]
After creating a new device in the config bits file and giving the project the correct linker files, I cannot load a program onto this pic using bullycpp. Any kind of help if useful.

**Comment by thirtythreeforty** [comment]
Hello!  So after adding the config line, are you providing it to the program via a rebuild or via `--piclist`?

At what point does the process fail?

**Comment by Keritan** [comment]
I am applying it via a rebiild. When I try to load a program on the pic, it
gives me an error message saying serial timeout has occurred.

**Comment by thirtythreeforty** [comment]
Hmm.  That suggests the bootloader isn't running... You've already burned the bootloader using a PICkit?

Can the legacy bootloader application communicate with the part?

**Comment by Keritan** [comment]
Yes I did burn the bootloader using the PICkit and I am not sure if the
part can communicate with the legacy bootloader application. Where can I
find that?

**Comment by thirtythreeforty** [comment]
Hey sorry for the radio silence... The legacy application is available on reesemicro.com, as part of their code tarball.

**Comment by thirtythreeforty** [comment]
Did you figure this out?

**Comment by Keritan** [comment]
I did not. I apologize for not responding. Got busy with something else
dealing with the project.

**Comment by thirtythreeforty** [comment]
I'm gonna close this but feel free to reopen it if you still need help.
