### ISSUE TITLE
UART1 Window Multi-Character Strings

### ISSUE THREAD

**Issue by Tuxprogrammer** [thirtythreeforty/bullycpp#25]
The UART data transfer window cannot send multiple characters at once in the latest revision. Also, you cannot paste strings into the UART data transfer window.

**Comment by thirtythreeforty** [comment]
Duplicate of #22?  This has been fixed in `master` and will be released as soon as I get some time.

**Comment by thirtythreeforty** [comment]
I'm gonna close this as a duplicate but if you mean something different feel free to reopen!
